[bot]
token = "MzE0Nzg1Njg0NzYwMDM1MzI4.DAcPVQ.AOaz6YCF0uLvz8DJ_ACAJjb56XQ"
HOST = "127.0.0.1"
PORT = 42424
update_channel_id = "314789381443682304"
bot_command_prefix = "!"
bot_description = "A bot used as front_end for an automation application.\nThere are a number of utility commands being showcased here."
[automation]
url_get = "http://localhost:8000/light-natural"
url_post = "http://localhost:8000/light"
